Device.create(model: 'iPad', name: 'Pro 9.7-inch', network: 'ATT', size: 32, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Device.create(model: 'iPhone', name: '6s Plus', network: 'ATT', size: 16, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Device.create(model: 'Galaxy', name: 'S7', network: 'ATT', size: 32, image: '/images/galaxy-s7.png', price_cents: 20000)


Ipad.create(name: 'Pro 9.7-inch', network: 'ATT', size: 32, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'ATT', size: 256, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'ATT', size: 128, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Sprint', size: 32, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Sprint', size: 256, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Sprint', size: 128, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'T-Mobile', size: 32, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'T-Mobile', size: 256, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'T-Mobile', size: 128, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Verizon', size: 32, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Verizon', size: 256, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Verizon', size: 128, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Other', size: 32, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Other', size: 256, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 9.7-inch', network: 'Other', size: 128, image: '/images/ipad-pro-9-7.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'ATT', size: 32, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'ATT', size: 256, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'ATT', size: 128, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Sprint', size: 32, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Sprint', size: 256, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Sprint', size: 128, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'T-Mobile', size: 32, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'T-Mobile', size: 256, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'T-Mobile', size: 128, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Verizon', size: 32, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Verizon', size: 256, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Verizon', size: 128, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Other', size: 32, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Other', size: 256, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Pro 12.9-inch', network: 'Other', size: 128, image: '/images/ipad-pro.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'ATT', size: 16, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'ATT', size: 64, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'ATT', size: 128, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Sprint', size: 16, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Sprint', size: 64, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Sprint', size: 128, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'T-Mobile', size: 16, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'T-Mobile', size: 64, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'T-Mobile', size: 128, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Verizon', size: 16, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Verizon', size: 64, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Verizon', size: 128, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Other', size: 16, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Other', size: 64, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air 2', network: 'Other', size: 128, image: '/images/ipad-air2.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'ATT', size: 16, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'ATT', size: 32, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'ATT', size: 64, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'ATT', size: 128, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Sprint', size: 16, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Sprint', size: 32, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Sprint', size: 64, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Sprint', size: 128, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'T-Mobile', size: 16, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'T-Mobile', size: 32, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'T-Mobile', size: 64, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'T-Mobile', size: 128, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Verizon', size: 16, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Verizon', size: 32, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Verizon', size: 64, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Verizon', size: 128, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Other', size: 16, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Other', size: 32, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Other', size: 64, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'Air', network: 'Other', size: 128, image: '/images/ipad-air.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'ATT', size: 16, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'ATT', size: 64, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'ATT', size: 128, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Sprint', size: 16, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Sprint', size: 64, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Sprint', size: 128, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'T-Mobile', size: 16, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'T-Mobile', size: 64, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'T-Mobile', size: 128, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Verizon', size: 16, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Verizon', size: 64, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Verizon', size: 128, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Other', size: 16, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Other', size: 64, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 4', network: 'Other', size: 128, image: '/images/ipad-mini4.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'ATT', size: 16, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'ATT', size: 64, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'ATT', size: 128, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Sprint', size: 16, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Sprint', size: 64, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Sprint', size: 128, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'T-Mobile', size: 16, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'T-Mobile', size: 64, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'T-Mobile', size: 128, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Verizon', size: 16, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Verizon', size: 64, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Verizon', size: 128, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Other', size: 16, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Other', size: 64, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 3', network: 'Other', size: 128, image: '/images/ipad-mini3.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'ATT', size: 16, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'ATT', size: 32, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'ATT', size: 64, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'ATT', size: 128, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Sprint', size: 16, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Sprint', size: 32, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Sprint', size: 64, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Sprint', size: 128, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'T-Mobile', size: 16, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'T-Mobile', size: 32, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'T-Mobile', size: 64, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'T-Mobile', size: 128, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Verizon', size: 16, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Verizon', size: 32, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Verizon', size: 64, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Verizon', size: 128, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Other', size: 16, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Other', size: 32, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Other', size: 64, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini 2', network: 'Other', size: 128, image: '/images/ipad-mini2.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'ATT', size: 16, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'ATT', size: 64, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'ATT', size: 32, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Sprint', size: 16, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Sprint', size: 64, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Sprint', size: 32, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'T-Mobile', size: 16, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'T-Mobile', size: 64, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'T-Mobile', size: 32, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Verizon', size: 16, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Verizon', size: 64, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Verizon', size: 32, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Other', size: 16, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Other', size: 64, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: 'mini', network: 'Other', size: 32, image: '/images/ipad-mini.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'ATT', size: 16, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'ATT', size: 32, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'ATT', size: 64, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'ATT', size: 128, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Sprint', size: 16, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Sprint', size: 32, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Sprint', size: 64, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Sprint', size: 128, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'T-Mobile', size: 16, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'T-Mobile', size: 32, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'T-Mobile', size: 64, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'T-Mobile', size: 128, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Verizon', size: 16, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Verizon', size: 32, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Verizon', size: 64, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Verizon', size: 128, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Other', size: 16, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Other', size: 32, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Other', size: 64, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '4th generation', network: 'Other', size: 128, image: '/images/ipad-4gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'ATT', size: 16, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'ATT', size: 64, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'ATT', size: 32, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Sprint', size: 16, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Sprint', size: 64, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Sprint', size: 32, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'T-Mobile', size: 16, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'T-Mobile', size: 64, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'T-Mobile', size: 32, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Verizon', size: 16, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Verizon', size: 64, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Verizon', size: 32, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Other', size: 16, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Other', size: 64, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '3rd generation', network: 'Other', size: 32, image: '/images/ipad-3gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'ATT', size: 16, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'ATT', size: 64, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'ATT', size: 32, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Sprint', size: 16, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Sprint', size: 64, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Sprint', size: 32, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'T-Mobile', size: 16, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'T-Mobile', size: 64, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'T-Mobile', size: 32, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Verizon', size: 16, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Verizon', size: 64, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Verizon', size: 32, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Other', size: 16, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Other', size: 64, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: '2nd generation', network: 'Other', size: 32, image: '/images/ipad-2gen.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'ATT', size: 16, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'ATT', size: 64, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'ATT', size: 32, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Sprint', size: 16, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Sprint', size: 64, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Sprint', size: 32, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'T-Mobile', size: 16, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'T-Mobile', size: 64, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'T-Mobile', size: 32, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Verizon', size: 16, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Verizon', size: 64, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Verizon', size: 32, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Other', size: 16, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Other', size: 64, image: '/images/ipad.jpg', price_cents: 20000)
Ipad.create(name: 'original', network: 'Other', size: 32, image: '/images/ipad.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'ATT', size: 16, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'ATT', size: 64, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'ATT', size: 128, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Sprint', size: 16, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Sprint', size: 64, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Sprint', size: 128, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'T-Mobile', size: 16, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'T-Mobile', size: 64, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'T-Mobile', size: 128, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Verizon', size: 16, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Verizon', size: 64, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Verizon', size: 128, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Other', size: 16, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Other', size: 64, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s Plus', network: 'Other', size: 128, image: '/images/iphone-6splus.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'ATT', size: 16, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'ATT', size: 64, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'ATT', size: 128, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Sprint', size: 16, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Sprint', size: 64, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Sprint', size: 128, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'T-Mobile', size: 16, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'T-Mobile', size: 64, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'T-Mobile', size: 128, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Verizon', size: 16, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Verizon', size: 64, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Verizon', size: 128, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Other', size: 16, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Other', size: 64, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6s', network: 'Other', size: 128, image: '/images/iphone-6s.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'ATT', size: 16, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'ATT', size: 64, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'ATT', size: 128, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Sprint', size: 16, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Sprint', size: 64, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Sprint', size: 128, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'T-Mobile', size: 16, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'T-Mobile', size: 64, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'T-Mobile', size: 128, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Verizon', size: 16, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Verizon', size: 64, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Verizon', size: 128, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Other', size: 16, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Other', size: 64, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6 Plus', network: 'Other', size: 128, image: '/images/iphone6plus.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'ATT', size: 16, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'ATT', size: 64, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'ATT', size: 128, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Sprint', size: 16, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Sprint', size: 64, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Sprint', size: 128, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'T-Mobile', size: 16, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'T-Mobile', size: 64, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'T-Mobile', size: 128, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Verizon', size: 16, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Verizon', size: 64, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Verizon', size: 128, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Other', size: 16, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Other', size: 64, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: '6', network: 'Other', size: 128, image: '/images/iphone6.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'ATT', size: 16, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'ATT', size: 64, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'Sprint', size: 16, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'Sprint', size: 64, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'T-Mobile', size: 16, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'T-Mobile', size: 64, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'Verizon', size: 16, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'Verizon', size: 64, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'Other', size: 16, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: 'SE', network: 'Other', size: 64, image: '/images/iphone-se.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'ATT', size: 16, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'ATT', size: 64, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'ATT', size: 32, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Sprint', size: 16, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Sprint', size: 64, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Sprint', size: 32, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'T-Mobile', size: 16, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'T-Mobile', size: 64, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'T-Mobile', size: 32, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Verizon', size: 16, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Verizon', size: 64, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Verizon', size: 32, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Other', size: 16, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Other', size: 64, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5s', network: 'Other', size: 32, image: '/images/iphone5s.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'ATT', size: 16, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'ATT', size: 8, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'ATT', size: 32, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Sprint', size: 16, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Sprint', size: 8, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Sprint', size: 32, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'T-Mobile', size: 16, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'T-Mobile', size: 8, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'T-Mobile', size: 32, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Verizon', size: 16, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Verizon', size: 8, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Verizon', size: 32, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Other', size: 16, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Other', size: 8, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5c', network: 'Other', size: 32, image: '/images/iphone5c.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'ATT', size: 16, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'ATT', size: 64, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'ATT', size: 32, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Sprint', size: 16, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Sprint', size: 64, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Sprint', size: 32, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'T-Mobile', size: 16, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'T-Mobile', size: 64, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'T-Mobile', size: 32, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Verizon', size: 16, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Verizon', size: 64, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Verizon', size: 32, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Other', size: 16, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Other', size: 64, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '5', network: 'Other', size: 32, image: '/images/iphone5.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'ATT', size: 16, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'ATT', size: 64, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'ATT', size: 32, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'ATT', size: 8, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Sprint', size: 16, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Sprint', size: 64, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Sprint', size: 32, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Sprint', size: 8, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'T-Mobile', size: 16, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'T-Mobile', size: 64, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'T-Mobile', size: 32, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'T-Mobile', size: 8, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Verizon', size: 16, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Verizon', size: 64, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Verizon', size: 32, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Verizon', size: 8, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Other', size: 16, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Other', size: 64, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Other', size: 32, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4s', network: 'Other', size: 8, image: '/images/iphone4s.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'ATT', size: 16, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'ATT', size: 32, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'ATT', size: 8, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Sprint', size: 16, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Sprint', size: 32, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Sprint', size: 8, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'T-Mobile', size: 16, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'T-Mobile', size: 32, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'T-Mobile', size: 8, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Verizon', size: 16, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Verizon', size: 32, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Verizon', size: 8, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Other', size: 16, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Other', size: 32, image: '/images/iphone4.jpg', price_cents: 20000)
Iphone.create(name: '4', network: 'Other', size: 8, image: '/images/iphone4.jpg', price_cents: 20000)
Galaxy.create(name: 'S7', network: 'ATT', size: 32, image: '/images/galaxy-s7.png', price_cents: 20000)
Galaxy.create(name: 'S7', network: 'Sprint', size: 32, image: '/images/galaxy-s7.png', price_cents: 20000)
Galaxy.create(name: 'S7', network: 'T-Mobile', size: 32, image: '/images/galaxy-s7.png', price_cents: 20000)
Galaxy.create(name: 'S7', network: 'Verizon', size: 32, image: '/images/galaxy-s7.png', price_cents: 20000)
Galaxy.create(name: 'S7', network: 'Other', size: 32, image: '/images/galaxy-s7.png', price_cents: 20000)
Galaxy.create(name: 'S7 edge', network: 'ATT', size: 32, image: '/images/galaxy-s7edge.jpg', price_cents: 20000)
Galaxy.create(name: 'S7 edge', network: 'Sprint', size: 32, image: '/images/galaxy-s7edge.jpg', price_cents: 20000)
Galaxy.create(name: 'S7 edge', network: 'T-Mobile', size: 32, image: '/images/galaxy-s7edge.jpg', price_cents: 20000)
Galaxy.create(name: 'S7 edge', network: 'Verizon', size: 32, image: '/images/galaxy-s7edge.jpg', price_cents: 20000)
Galaxy.create(name: 'S7 edge', network: 'Other', size: 32, image: '/images/galaxy-s7edge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6', network: 'ATT', size: 32, image: '/images/galaxy-s6.png', price_cents: 20000)
Galaxy.create(name: 'S6', network: 'Sprint', size: 32, image: '/images/galaxy-s6.png', price_cents: 20000)
Galaxy.create(name: 'S6', network: 'T-Mobile', size: 32, image: '/images/galaxy-s6.png', price_cents: 20000)
Galaxy.create(name: 'S6', network: 'Verizon', size: 32, image: '/images/galaxy-s6.png', price_cents: 20000)
Galaxy.create(name: 'S6', network: 'Other', size: 32, image: '/images/galaxy-s6.png', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'ATT', size: 32, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'Sprint', size: 32, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'T-Mobile', size: 32, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'Verizon', size: 32, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'Other', size: 32, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'ATT', size: 128, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'Sprint', size: 128, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'T-Mobile', size: 128, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'Verizon', size: 128, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S6 edge', network: 'Other', size: 128, image: '/images/galaxy-6sedge.jpg', price_cents: 20000)
Galaxy.create(name: 'S5', network: 'ATT', size: 32, image: '/images/galaxy-s5.jpg', price_cents: 20000)
Galaxy.create(name: 'S5', network: 'Sprint', size: 32, image: '/images/galaxy-s5.jpg', price_cents: 20000)
Galaxy.create(name: 'S5', network: 'T-Mobile', size: 32, image: '/images/galaxy-s5.jpg', price_cents: 20000)
Galaxy.create(name: 'S5', network: 'Verizon', size: 32, image: '/images/galaxy-s5.jpg', price_cents: 20000)
Galaxy.create(name: 'S5', network: 'Other', size: 32, image: '/images/galaxy-s5.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'ATT', size: 32, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'Sprint', size: 32, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'T-Mobile', size: 32, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'Verizon', size: 32, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'Other', size: 32, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'ATT', size: 16, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'Sprint', size: 16, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'T-Mobile', size: 16, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'Verizon', size: 16, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'S4', network: 'Other', size: 16, image: '/images/galaxy-s4.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'ATT', size: 32, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'Sprint', size: 32, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'T-Mobile', size: 32, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'Verizon', size: 32, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'Other', size: 32, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'ATT', size: 64, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'Sprint', size: 64, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'T-Mobile', size: 64, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'Verizon', size: 64, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 5', network: 'Other', size: 64, image: '/images/galaxy-note5.jpg', price_cents: 20000)
Galaxy.create(name: 'Note edge', network: 'ATT', size: 32, image: '/images/galaxy-note-edge.jpg', price_cents: 20000)
Galaxy.create(name: 'Note edge', network: 'Sprint', size: 32, image: '/images/galaxy-note-edge.jpg', price_cents: 20000)
Galaxy.create(name: 'Note edge', network: 'T-Mobile', size: 32, image: '/images/galaxy-note-edge.jpg', price_cents: 20000)
Galaxy.create(name: 'Note edge', network: 'Verizon', size: 32, image: '/images/galaxy-note-edge.jpg', price_cents: 20000)
Galaxy.create(name: 'Note edge', network: 'Other', size: 32, image: '/images/galaxy-note-edge.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 4', network: 'ATT', size: 32, image: '/images/galaxy-note4.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 4', network: 'Sprint', size: 32, image: '/images/galaxy-note4.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 4', network: 'T-Mobile', size: 32, image: '/images/galaxy-note4.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 4', network: 'Verizon', size: 32, image: '/images/galaxy-note4.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 4', network: 'Other', size: 32, image: '/images/galaxy-note4.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 3', network: 'ATT', size: 32, image: '/images/galaxy-note3.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 3', network: 'Sprint', size: 32, image: '/images/galaxy-note3.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 3', network: 'T-Mobile', size: 32, image: '/images/galaxy-note3.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 3', network: 'Verizon', size: 32, image: '/images/galaxy-note3.jpg', price_cents: 20000)
Galaxy.create(name: 'Note 3', network: 'Other', size: 32, image: '/images/galaxy-note3.jpg', price_cents: 20000)

AdminUser.create!(email: 'psswf1172@yahoo.com', password: 'password', password_confirmation: 'password')
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')
